### ISSUE TITLE
请问不管router在哪个国家，这些ip都是同样的?  还是不同国家会有不同？

### ISSUE THREAD

**Issue by bk111** [QiuSimons/Netflix_IP#3]
请问不管router在哪个国家，这些ip都是同样的?  还是不同国家会有不同？

**Comment by QiuSimons** [comment]
一般都是相同的，不过如果你的节点网络供应商有劫持的情况（比如劫持到自有cdn网络上的话
就会有其他ip，概率不大就是了，听说墨西哥有这种情况.....
