### ISSUE TITLE
aws 是否应该排除中国区的IP？

### ISSUE THREAD

**Issue by PMExtra** [QiuSimons/Netflix_IP#5]
我发现 NETFLIX & AWS 的 IP 列表中包含了很多北京光环新网的IP，这些应该和 NETFLIX 没有任何关系，也没必要FQ吧？
比如
54.222.128.0/17
54.223.0.0/16
都是北京光环新网的IP段。

**Comment by Saxon-Sun** [comment]
我也发现这个问题了 导致我监控服务商ip有时候跳的这个ip段就断网了 希望能排除中国区的IP

**Comment by QiuSimons** [comment]
欢迎提交pr

**Comment by QiuSimons** [comment]
修复了

**Comment by Saxon-Sun** [comment]
稳😚
